name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Config clear
      run: php artisan config:clear
    - name: Route Cache
      run: php artisan route:cache
    - name: php-cs-fixer
      run: ./vendor/bin/php-cs-fixer fix --dry-run --diff
    - name: var_dump checker for app folder
      run: ./vendor/bin/var-dump-check --no-colors --tracy --symfony --laravel app/
    - name: var_dump checker for database folder
      run: ./vendor/bin/var-dump-check --no-colors --tracy --symfony --laravel database/
    - name: var_dump checker for resources folder
      run: ./vendor/bin/var-dump-check --no-colors --tracy --symfony --laravel resources/
    - name: var_dump checker for tests folder
      run: ./vendor/bin/var-dump-check --no-colors --tracy --symfony --laravel tests/
    - name: Parallel lint
      run: ./vendor/bin/parallel-lint --exclude vendor .
    - name: phpstan Analyse
      run: ./vendor/phpstan/phpstan/phpstan analyse
